### ISSUE TITLE
minify task should minify all js files in dist folder

### ISSUE THREAD

**Issue by edwardoparearyee** [thisissoon/angular2-start#20]
At the moment all the code for our example is in `src/app/app.ts` this was just meant to be temporary while we build the project. Ideally it would be split so each component would be in it own file within it's own folder inside the `app` folder e.g. `src/app/about/about.ts`,  `src/app/home/home.ts` etc... similar to this: https://github.com/AngularClass/angular2-webpack-starter/tree/master/src/app

**Comment by jamesjwarren** [comment]
Yeh working on that atm, its tricky. I thought it could be done with find like:
`find dist/src/app -name '*[!.min][!.spec].js' -exec uglifyjs {} -m --compress='sequences,properties,dead_code,drop_debugger,conditionals,comparisons,booleans,unused,if_return,join_vars,warnings,drop_console' --preamble '/*! '$npm_package_name' - v'$npm_package_version' - '$(date +%Y-%m-%d)' */' -o {}.min.js --source-map {}.min.js.map --in-source-map {}.map \\;`

But it doesn't work very well so trying to find another solution.

**Comment by jamesjwarren** [comment]
@edwardoparearyee I think this is were grunt/gulp can make things easier

**Comment by edwardoparearyee** [comment]
@jamesjwarren I agree but lets leave it for now as minification isn't as much of an issue as we are loading modules dynamically anyway. 

We can wait and see how other are bundling their angular 2 apps and follow their leads.

**Comment by jamesjwarren** [comment]
yeh I agree :+1:

This is another popular starter using systemjs + gulp but there pipeline is pretty complicated: https://github.com/mgechev/angular2-seed

**Comment by edwardoparearyee** [comment]
I had looked at that project and the possibility of using gulp as a lot are using it for angular 2 but I've never been a big fan of gulp as their config syntax is mostly javascript based compared to grunt which is more like json.

Plus I wanted to avoid task runners so we can try using node modules directly, but if thats making our life harder we can change.

**Comment by edwardoparearyee** [comment]
Now that we are using webpack to bundle the app we can actually do minification using webpack

**Comment by edwardoparearyee** [comment]
So we aren't using webpack anymore but we should be able to use angular-cli to build a production ready  version once they implement it.
