### ISSUE TITLE
Should we switch to webpack?

### ISSUE THREAD

**Issue by edwardoparearyee** [thisissoon/angular2-start#24]
I'm having a really hard time getting tests running using systemjs, I think it would be easier to use webpack going forward as there are a lot of example projects using such as this [one](https://angularclass.github.io/angular2-webpack-starter/) meaning we can get/find more help if needed with running angular 2 as our project would more closely follow this one.

**Comment by jamesjwarren** [comment]
That's frustrating! Have you seen any of their production bundling techniques wondering if these might help: https://github.com/systemjs/systemjs/blob/master/docs/production-workflows.md 

But yeh, if it's a real pain I agree it makes sense to follow an exisiting example and try webpack.

**Comment by edwardoparearyee** [comment]
Looking more into this, it appears to be an issue with the shim i'm using to run the tests rather than systemjs which makes sense as the app runs fine with `npm start` so will persist with it for now.
