### ISSUE TITLE
Don't use styles in angular for now

### ISSUE THREAD

**Issue by edwardoparearyee** [thisissoon/angular2-start#27]
I find it very restrictive at the moment because it basically limits the ability to add global styles. So maybe for now we should go back to the way we did styles in the [angular-start](https://github.com/thisissoon/angular-start) project where we would compile all our less into one css file and handle modules in less.

**Comment by jamesjwarren** [comment]
Angular2 is using shadow DOM (albeit an emulated version atm) to encapsulate components as this is part of the web component standard in general, to make components more portable and re-usable.

Good article on this here:
http://blog.thoughtram.io/angular/2015/06/29/shadow-dom-strategies-in-angular2.html

I think it makes sense to use this for specific component styles in place of the `modules/` we had before, as the encapsulation would help us there. Can't we combine this technique with global styles too, so we have our core styles like type, grid etc. compiled as before?

**Comment by edwardoparearyee** [comment]
Nice article, I understand the advantages and my initial thought to add global styles was to use both but thought it would be confusing using both component styles and global styles but I don't mind trying both.

**Comment by edwardoparearyee** [comment]
so i agree we should be using styles in components to replace our previous "{device-type}/modules" folder in less.
